---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-inventory-metadata
spec:
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - port: {{ .Values.httpPortMeta | int }}
          protocol: TCP
  podSelector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
